apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mcbe-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcbe-deployment
  labels:
    app: mcbe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcbe
  template:
    metadata:
      labels:
        app: mcbe
    spec:
      containers:
      - name: mcbe
        image: tuna2134/mcbe
        ports:
        - containerPort: 19132
        volumeMounts:
        - name: data
          mountPath: "/app/worlds"
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: mcbe-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mcbe-service
spec:
  selector:
    app: mcbe
  ports:
  - protocol: UDP
    port: 19132
    targetPort: 19132
    name: mc
  type: LoadBalancer
