apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mcbe-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcbe-deployment
  labels:
    app: mcbe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcbe
  template:
    metadata:
      labels:
        app: mcbe
    spec:
      containers:
      - name: mcbe
        image: ghcr.io/mc-fdc-dev/minecraft-be-image
        ports:
        - containerPort: 19132
        volumeMounts:
        - name: data
          mountPath: "/app/worlds"
        - name: config-perms
          mountPath: "/app/permissions.json"
          subPath: "permissions.json"
          readOnly: false
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: mcbe-pvc
      - name: config-perms
        configMap:
          name: mcbe-config
          items:
          - key: "permissions.json"
            path: "permissons.json"
---
apiVersion: v1
kind: Service
metadata:
  name: mcbe-service
spec:
  selector:
    app: mcbe
  ports:
  - protocol: UDP
    port: 19132
    targetPort: 19132
    name: mc
  - protocol: TCP
    port: 19132
    targetPort: 19132
    name: mc-tcp
  type: LoadBalancer
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mcbe-config
data:
  permissions.json: |
    [
      {
        "permission": "operator",
        "xuid": "2535449888211118"
      }
    ]
